name: Deploy Lambda Function
on:
  push:
    paths:
      - "./insights-services/functions/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Deploy Analyze Lambda Function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          role-session-name: GithubActionsDeploy
      - name: Setup Python
        uses: actions/setup-python@v4.7.0
      - name: Install cargo-lambda
        run: pip3 install cargo-lambda
      - name: Build Lambda Function
        working-directory: ./insights-services/functions
        run: cargo lambda build --release --arm64 --output-format zip
      - name: Deploy Lambda Function
        working-directory: ./insights-services
        run: aws lambda update-function-code --function-name analyze-demo --zip-file fileb://./target/lambda/functions/bootstrap.zip
